Setup mobile skeleton
mike2611/portfolio pull request #1
Opened 2021-08-12 18:52 UTC by mike2611

Added setup for the portfolio and skeleton for the mobile version of the portfolio.

2021-08-12 20:11 UTC, barackm requested changes
Hi @mike2611, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 
![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 20:11 UTC, barackm commented on README.md
> +## Live Demo
- [x] This is a very nice job on your README, but I think it can be good to remove the Live Demo section if it is not yet available. because this may confuse people. Please let's fix that 👍

2021-08-12 20:11 UTC, barackm commented on index.html
> +        <ul id="items-container">
- [x] Kindly let's use an anchor `<a>` tag for the logo instead of the `<div>`. This is because the logo is supposed to be a link or a button which means it's something we can click on, but the `<div>` tag is not going to give us that behavior.

2021-08-12 20:11 UTC, barackm commented on index.html
> +        </div>
- [x] This is a great job adding links to your header. But in order to keep the code clean by using semantic HTML, it is better to wrap all the links with the `<nav>` tag. like this: 👇 
```
<nav>
   <ul></ul>
   <button id="header-menu" type="button">
        <i class="material-icons">menu</i>
    <button>
</nav>
```
- [x] Also your header menu or hamburger should actually be something on which we can click in order to fire some actions... for example: show or hide the links by clicking on the hamburger menu. This is the reason why it should be either an anchor tag `<a>` or a `<button>` instead of a `<div>` like in the example above 👆 . Please let's fix this issue as well 😉

2021-08-12 20:11 UTC, barackm commented on index.html
> +        </nav>
- [x] Great job on adding social media icons to your portfolio, However, these icons are supposed to be links (clickable) because they should contain the URL of your profile at that specific social media website. 
- [x] After having the icons as links, they should be wrapped with an unordered list `<ul>` tag, because it's actually a list of links, so we should finally have something like this 👇 
```
<ul>
    <li>
        <a href="https://www......">
            <img src="images/medium.png" alt="medium">
        </a>
    </li>
     <li>
        <a href="https://www......">
            <img src="images/twitter.png" alt="twitter">
        </a>
    </li>
</ul>
```

This will make your code more semantic 😉 .

2021-08-12 20:11 UTC, barackm commented on css/styles.css
> +
- [x] This is good to think about media queries `@media`. But the approach that is required to build the portfolio is actually **` Mobile First`** This means we should not have media queries for the mobile view, they should be visible only for the tablet and desktop screen sizes.

2021-08-12 20:11 UTC, barackm commented on css/styles.css
> +}
- [x] This is a great thing using CSS flexbox to layout your content. However, there is something we need to fix for your code to be more cleaner.  I can see that you have used the property `display: flex` 
and `font-family: Inter, Arial, Helvetica, sans-serif;` at multiple places, please let's use DRY(Don't repeat yourself) to keep the code clean by extracting the property into a separate class that can be reused at multiple places, see example below: 

- CSS file
```
.d-flex {
  display: flex;
}

.heading-font {
    font-family: Inter, Arial, Helvetica, sans-serif;
}
 
.flex-center {
  align-items: center;
  justify-content: center;
}
```
- HTML file
```
<div class="d-flex flex-center heading-font">{your content}</div>
```

You can do the same for all the properties that seem to be repeated at multiple places.

2021-08-12 20:11 UTC, barackm commented on index.html
> +    <div id="principal-container">
- [x] The container wrapping the second section of the portfolio should be a `<section>` tag instead of a `<div>` this is because sections are used to divide our application into sections containing a big content, just like this headline section. So please let's use the `<section>` tag instead of the `<div>` 👍

2021-08-12 20:11 UTC, barackm commented on index.html
> +</html>
- [ ] This is so great the efforts you made to have the same design as the one in Figma, but I can see that there are some areas where you did not follow the Figma template, Please let's use the same `fonts`, `colors`, spaces around your logo and hamburger. see the difference below 👇 

- Your portfolio
![image](https://user-images.githubusercontent.com/55465133/129260425-59554f12-eb86-49f0-b53c-309db3596023.png)

✅  The Figma template
![image](https://user-images.githubusercontent.com/55465133/129262811-c8b8ebd6-1b9a-403b-a9b3-e014de1d7075.png)

Please let's make some efforts again and make the design look like the one in the Figma template 👍

2021-08-13 04:03 UTC, AbdumurodovaZulfizar requested changes
Hello @mike2611, I am @AbdumurodovaZulfizar, your reviewer for this project :wave:

Congratulations on doing an awesome project and thanks for implementing the required changes by the previous reviewer, there is really little distance between you and approval💥
**TO HIGHLIGHT:**

- You have set up linters correctly and there are no errors✅
- You have written descriptive comments with the correct tense✅
- Your README.md is professional✅


### **CHANGES REQUIRED ♻️ 🛑**


**Look through the comments below 👇 for required changes**


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
<hr>

Happy Coding 🔥🔥🔥
The review was done by @AbdumurodovaZulfizar
If there is anything that is not 💯% clear don't hesitate to hit me on:
[LinkedIn](https://www.linkedin.com/in/zulfizarabdumurodova/) | [Email](abdumurodovazulfizar77@gmail.com) | @Zulfizar on slack

<hr>

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 04:03 UTC, AbdumurodovaZulfizar commented on README.md
> +
- [x] **REQUIRED:** Change this sentence according to your project, because it is not good for professionalism. From there other visitors of your project will exactly realize that you have copied READE.md from another project.

2021-08-13 04:03 UTC, AbdumurodovaZulfizar commented on index.html
> +        </a>
- [x] **REQUIRED:** The `John Doe` is a name actually😊, you should replace it with your name. Also the same for the main title is showing `Alex`, You will use this portfolio while searching and accepting a job, it is not good for professionalism if you show different names.

_Do not forget to change the image on your README.md after replacing the names, because also README.md s is showing different names._

2021-08-13 04:43 UTC, carlos-ssh approved these changes
Hi @mike2611 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 13:01 UTC, merged